#include "MTLReader.h"
#include <fstream>
#include <sstream>
#include <iostream>
#include <iomanip>

MTLReader::MTLReader()
{
}


MTLReader::~MTLReader()
{
}

MaterialMapping MTLReader::read(std::string path)
{
	MaterialMapping materialMapping;
	Material* currentMaterial = new Material();
	std::ifstream arq(path);

	if (!arq.is_open()) {
		std::cout << "File could not be loaded. Wrong path!" << std::endl;
	}

	while (!arq.eof()) {
		std::string line;
		getline(arq, line);
		std::stringstream sline;
		sline << line;
		std::string temp;
		sline >> temp;
		if (temp == "Kd") {
			float x, y, z;
			sline >> x >> y >> z;
			currentMaterial->kd = (glm::vec3(x, y, z));
		}
		else if (temp == "Ka") {
			float x, y, z;
			sline >> x >> y >> z;
			currentMaterial->ka = (glm::vec3(x, y, z));
		}
		else if (temp == "Ks") {
			float x, y, z;
			sline >> x >> y >> z;
			currentMaterial->ks = (glm::vec3(x, y, z));
		}
		else if (temp == "Ni") {
			float x;
			sline >> x;
			currentMaterial->ni = (x);
		}
		else if (temp == "Ns") {
			float x;
			sline >> x;
			currentMaterial->ns = (x);
		}
		else if (temp == "map_Kd") {
			std::string x;
			sline >> x;
			currentMaterial->map_kd = (x);
		}
		else if (temp == "newmtl") {
			std::string materialName;
			sline >> materialName;
			materialMapping[materialName] = Material();
			currentMaterial = &materialMapping[materialName];
		}
	}

	arq.close();
	return materialMapping;
}

void MTLReader::write(std::string path, MaterialMapping * materialMap)
{
	std::ofstream file;
	file.exceptions(std::ofstream::badbit);
	try {

		file.open(path);

		if (!file.is_open()) {
			std::cout << "ERROR::MTLREADER::PATH ERROR";
		}


		// Headers

		file << "# Generated by obj-loader \n";
		file << "# Materials count: " << materialMap->size() << "\n\n";

		// Materials

		for (MaterialMapping::iterator it = materialMap->begin(); it != materialMap->end(); ++it)
		{
			file << "\n\n";

			// Name
			file << "newmtl " << it->second.name << '\n';

			// k's
			glm::vec3 ka = it->second.ka;
			glm::vec3 kd = it->second.kd;
			glm::vec3 ks = it->second.ks;

			file << "Ka ";
			file << std::fixed << std::setprecision(6) <<
				ka.x << " " << ka.y << " " << ka.z << '\n';

			file << "Kd ";
			file << std::fixed << std::setprecision(6) <<
				kd.x << " " << kd.y << " " << kd.z << '\n';

			file << "Ks ";
			file << std::fixed << std::setprecision(6) <<
				ks.x << " " << ks.y << " " << ks.z << '\n';

			// N's
			// NS
			file << "Ns ";
			file << std::fixed << std::setprecision(6) <<
				it->second.ns << '\n';

			// NI
			file << "Ni ";
			file << std::fixed << std::setprecision(6) <<
				it->second.ni << '\n';

			// Maps
			// Map Kd
			if (it->second.map_kd != "") {
				file << "map_Kd ";
				file << it->second.map_kd << '\n';
			}

		}
	}
	catch (const std::ofstream::failure& e) {

		if (!file.eof()) {
			std::cout << "ERROR::MTLREADER::FILE NOT SUCCESUFULLY WRITTEN" << std::endl;
			file.close();
		}

	}
	catch (std::exception& e) {
		std::cout << e.what() << std::endl;
		file.close();
	}
}
